services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3005 -b '0.0.0.0'"
    image: car_policies_web
    container_name: car_policies_web
    volumes:
      - .:/rails-on-car-policies/
    env_file:
      - .env
    ports:
      - "3005:3005"
    depends_on:
      - db
      - sneakers
    networks:
      - policy-service
      - private

  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - private

  sneakers:
    build:
      context: .
    command: bash -c 'bundle exec rake sneakers:run'
    volumes:
      - .:/rails-on-car-policies/
    env_file:
      - .env
    networks:
      - policy-service
      - private

volumes:
  data:

networks:
  private:
    external: false
  policy-service:
    external: true
