services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: car_policies_web
    container_name: car_policies_web
    volumes:
      - .:/rails-on-car-policies/
    ports:
      - "3000:3000"
    networks:
      - policy-service
    depends_on:
      - db
      - sneakers

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - policy-service


  sneakers:
    build:
      context: .
    command: bash -c 'bundle exec rake sneakers:run'
    volumes:
      - .:/rails-on-car-policies/
    environment:
      # - RABBITMQ_USERNAME=user
      # - RABBITMQ_PASSWORD=password
      - RABBITMQ_HOSTNAME=rabbitmq
    networks:
      - policy-service

networks:
  policy-service:
    name: policy-service
